name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 19.x
      uses: actions/setup-node@v1
      with:
        node-version: 19.x
    - name: Build
      run: npm ci
    - name: Compile
      run: npm run compile
      env:
        CI: true
    - name: Lint
      run: npm run lint
      env:
        CI: true
